### ISSUE TITLE
Signal handlers in the main loop might be a problem

### ISSUE THREAD

**Issue by dstathis** [canonical/cos-alerter#24]
### Bug Description

Signal handlers defined in the main loop may cause execution to stop forever. If this is true, we need to run the SIGUSR1 handler in its own thread.

### To Reproduce

Found via code inspection.

### Environment

-

### Relevant log output

```shell
-
```

**Comment by dstathis** [comment]
@rbarry82
It seems there is no issue here. From the python [signal docs](https://docs.python.org/3/library/signal.html#signals-and-threads):
```
Signals and threads
Python signal handlers are always executed in the main Python thread of the main interpreter, even if the signal was received in another thread. This means that signals can’t be used as a means of inter-thread communication. You can use the synchronization primitives from the threading module instead.

Besides, only the main thread of the main interpreter is allowed to set a new signal handler.
```

You can run the following script to convince yourself that execution does indeed continue after handling a signal:
```
#!/usr/bin/env python3

import signal
import time


def handle_sigusr1(_, __):
    print("sigusr1 handled")


signal.signal(signal.SIGUSR1, handle_sigusr1)
print("Waiting for signal")
time.sleep(15)
print("Exiting")
```

**Comment by rbarry82** [comment]
The question isn't "does execution continue?" It's "how does execution continue gracefully?" The trivial example works. Complex ones may not.

pthreads are blocking calls. If you start a thread and `.join()`, the signal will not come in. Conversely, if you want to propagate a "re-load the config" (or exit gracefully, or whatever) to threads, [`pthread_kill`](https://docs.python.org/3/library/signal.html#signal.pthread_kill) needs to be used. 

The point of threading in daemonizing is so logging status, reloading config, and otherwise being responsive can still occur even while some blocking operation (which in normal Python is basically everything), right? [PEP419](https://peps.python.org/pep-0419/) (which was not implemented) is explicitly about this problem -- `__exit__` is not guaranteed to be called, and the fcntl may stay locked. Forever. Or at least until it's restarted. 

Do we care about that on a `KeyboardInterrupt`? Maybe not. But it's not as clear cut as the docs make it seem.

If we want this to be resilient (we do), it's about establishing some baseline:
* Output/logging should not stop or pause when a notification is being sent (if there are a lot of receivers and they all take the maximum possible amount of time, how long will it be until the last one filters in or logs are sent?)
* Neither handling of signals (and propagation via `threading.Event`, `threading.Queue`, or some other mechanism) nor waiting for `thread.join()` should block output or logging. Signal handlers/eventing should handle things as rapidly as possible and return to the loop. 
* Cleanup should be as assured as we can be, considering that [there are some... problems with it in Python](https://bugs.python.org/issue31388). No dangling locks.

It's very easy to make a casual assumption of "well, this runs in a container and it's a fixed problem space, so everything in one place is ok", but it's also not _that_ hard to make it behave like a daemon. The threading we have is a good start. 

The main thread can/should come up, handle whatever log messages, and start children. Adding an additional thread per notify destination (or having a threadpool and sending off destinations to a `threading.Queue` or using a semaphore and a re-entrant datastructure), maybe a thread to actually "read" the alerts (again, so some timeout/latency/unexpected exception in reaching the target, parallelizing monitoring multiple alertmanagers). 

Once we start doing _that_, and all the mainthread handler needs to do is dispatch something to other threads and return, it's ok. Until then, waiting for other threads to join (and if we don't wait, we don't have have any idea whether it actually _sent_ the notification -- commonly done by subclassing `threading.Thread` and setting instance variables which can be checked on the joined object, but we can kind of do it however) blocks. 

While we're handling a signal, we block logging/dispatching/joining. While we're waiting to join, we block signal handling/logging/dispatching. There's really no way around it. `SIGUSR1` calls `send_test_mail` which calls apprise to send it, and the entire main thread is locked up as long as that takes. If we were in a contextmanager, depending on what the signal/exception was (the PEP/bug above), we may or may not have left the fcntl lock is set, and nothing will be able to write to it. Even re-entering the contextmanager would get stuck waiting to lock -- that's what I meant about the signal handler not necessarily being able to step back into the frame: there are less guarantees than we'd like about the state of things.

I'd suggest thinking through what the design of this may look like when it's larger than a POC with a very small number of destinations (and a single AM to monitor via... whatever mechanism) and possible places where execution may get "stuck" or where doing one things may block another important thing from happening, such as signal handlers which perform potentially time-consuming operations and/or may have been ejected from a contextmanager without `__exit__` firing and the impact that may have on other things trying to update the state file/check AM/send other notifications/whatever. 

This doesn't need an immediate fix, but it is something we'll need to think about and do. The signal handler being in the main thread is not avoidable. The signal handler _doing things_ is. It may even be reasonable to use a mutex to lock some variable when the file lock happens and record the name/id of the thread so it can be unlocked if the handler is going to do something which takes a while and/or it's still locked when the handler is invoked.

**Comment by dstathis** [comment]
@rbarry82 I think the changes in #32 should resolve this issue since I moved the "main loop" logic into separate threads. Do you agree?
